// Multi-word phrases that should be treated as single units
export const MULTI_WORD_PHRASES = [
  // "There" constructions
  "there is",
  "there's", 
  "there are",
  "there is not",
  "there are not",
  "there isn't",
  "there aren't",
  "is there",
  "are there",
  "there was",
  "there were",
  "there was not",
  "there were not",
  "there wasn't",
  "there weren't",
  "was there",
  "were there",
  "there has been",
  "there have been",
  "there has not been",
  "there have not been",
  "there hasn't been",
  "there haven't been",
  "has there been",
  "have there been",
  "there had been",
  "there had not been",
  "there hadn't been",
  "had there been",
  "there will be",
  "there will not be",
  "there won't be",
  "will there be",
  "there would be",
  "there would not be",
  "there wouldn't be",
  "would there be",
  "there would have been",
  "there would not have been",
  "there wouldn't have been",
  "would there have been",
  "there can be",
  "there cannot be",
  "there can't be",
  "can there be",
  "there could be",
  "there could not be",
  "there couldn't be",
  "could there be",
  "there could have been",
  "there could not have been",
  "there couldn't have been",
  "could there have been",
  "there may be",
  "there may not be",
  "may there be",
  "there might be",
  "there might not be",
  "might there be",
  "there must be",
  "there must not be",
  "there mustn't be",
  "must there be",
  "there should be",
  "there should not be",
  "there shouldn't be",
  "should there be",
  "there should have been",
  "there should not have been",
  "there shouldn't have been",
  "should there have been",
  "there is going to be",
  "there are going to be",
  "there is not going to be",
  "there are not going to be",
  "there isn't going to be",
  "there aren't going to be",
  "is there going to be",
  "are there going to be",
  "there was going to be",
  "there were going to be",
  "there was not going to be",
  "there were not going to be",
  "there wasn't going to be",
  "there weren't going to be",
  "was there going to be",
  "were there going to be",
  "there used to be",
  "there did not use to be",
  "there didn't use to be",
  "did there use to be",
  "there is supposed to be",
  "there are supposed to be",
  "there is not supposed to be",
  "there are not supposed to be",
  "there isn't supposed to be",
  "there aren't supposed to be",
  "is there supposed to be",
  "are there supposed to be",
  "there was supposed to be",
  "there were supposed to be",
  "there was not supposed to be",
  "there were not supposed to be",
  "there wasn't supposed to be",
  "there weren't supposed to be",
  "was there supposed to be",
  "were there supposed to be",
  "there seems to be",
  "there seem to be",
  "there does not seem to be",
  "there do not seem to be",
  "there doesn't seem to be",
  "there don't seem to be",
  "does there seem to be",
  "do there seem to be",
  "there appears to be",
  "there appear to be",
  "there does not appear to be",
  "there do not appear to be",
  "there doesn't appear to be",
  "there don't appear to be",
  "does there appear to be",
  "do there appear to be",
  "there happens to be",
  "there happen to be",
  "there did not happen to be",
  "there didn't happen to be",
  "did there happen to be",
  "there turns out to be",
  "there turn out to be",
  "there did not turn out to be",
  "there didn't turn out to be",
  "did there turn out to be",
  "there continues to be",
  "there continue to be",
  "there began to be",
  "there has begun to be",
  "there have begun to be",
  "there tends to be",
  "there tend to be",
  "there is likely to be",
  "there are likely to be",
  "there is unlikely to be",
  "there are unlikely to be",
  "is there likely to be",
  "are there likely to be",
  "there is about to be",
  "there are about to be",
  "is there about to be",
  "are there about to be",
  "there is to be",
  "there are to be",
  "is there to be",
  "are there to be",
  "there exists",
  "there exist",
  "there existed",
  "there will exist",
  "there remains",
  "there remain",
  "there remained",
  "there arises",
  "there arise",
  "there arose",
  "there occurs",
  "there occur",
  "there occurred",
  
  // Phrasal verbs
  "get up",
  "get on",
  "get on with",
  "get off",
  "get in",
  "get out",
  "get over",
  "get by",
  "get back",
  "get away",
  "get around",
  "get ahead",
  "take off",
  "take out",
  "take up",
  "take over",
  "take back",
  "take down",
  "take in",
  "take on",
  "take apart",
  "take after",
  "take to",
  "take away",
  "put on",
  "put off",
  "put out",
  "put up",
  "put up with",
  "put together",
  "put through",
  "put away",
  "put back",
  "put down",
  "come back",
  "come in",
  "come out",
  "come up",
  "come up with",
  "come across",
  "come by",
  "come around",
  "come along",
  "come off",
  "come out with",
  "come up against",
  "go on",
  "go out",
  "go over",
  "go ahead",
  "go off",
  "go through",
  "go back",
  "go by",
  "go down",
  "go in for",
  "go without",
  "go along with",
  "make up",
  "make out",
  "make up for",
  "make for",
  "make of",
  "make off with",
  "make out to be",
  "give up",
  "give in",
  "give back",
  "give away",
  "give off",
  "turn on",
  "turn off",
  "turn up",
  "turn down",
  "turn into",
  "turn out",
  "turn over",
  "look for",
  "look after",
  "look forward to",
  "look up",
  "look into",
  "look over",
  "look through",
  "look out",
  "look out for",
  "look down on",
  "look up to",
  "run out",
  "run out of",
  "run into",
  "run over",
  "run through",
  "run across",
  "break down",
  "break up",
  "break in",
  "break into",
  "break out",
  "break off",
  "set up",
  "set off",
  "set out",
  "set aside",
  "set down",
  "bring up",
  "bring back",
  "bring about",
  "bring in",
  "bring out",
  "bring along",
  "call off",
  "call back",
  "call up",
  "call on",
  "hold on",
  "hold up",
  "hold back",
  "hold out",
  "find out",
  "keep on",
  "keep up",
  "keep up with",
  "keep at",
  "keep away",
  "keep back",
  "keep from",
  "keep off",
  "keep out",
  "pick up",
  "pick out",
  "pick on",
  "pick off",
  "show up",
  "show off",
  "work out",
  "carry on",
  "carry out",
  "carry on with",
  "cut off",
  "cut down",
  "cut down on",
  "cut out",
  "cut back",
  "fill in",
  "fill out",
  "fill up",
  "figure out",
  "point out",
  "check in",
  "check out",
  "check on",
  "check up on",
  "end up",
  "wind up",
  "turn up",
  "sort out",
  "clear up",
  "back up",
  "back down",
  "catch up",
  "catch on",
  "drop off",
  "drop out",
  "fall apart",
  "fall behind",
  "fall for",
  "fall out",
  "let down",
  "let in",
  "let off",
  "let out",
  "pass away",
  "pass out",
  "pay back",
  "pay off",
  "pull over",
  "pull up",
  "put aside",
  "put forward",
  "put up to",
  "show around",
  "shut down",
  "shut up",
  "sign up",
  "sit down",
  "sit up",
  "stand by",
  "stand for",
  "stand out",
  "stand up",
  "stand up for",
  "stick to",
  "stick with",
  "stick out",
  "think over",
  "think through",
  "try on",
  "turn around",
  "wake up",
  "wipe out",
  "write down",
  "write up",
  "wrap up",
  
  // Other common multi-word expressions
  "going to",
  "used to",
  "supposed to",
  "have been",
  "has been",
  "had been",
  "a lot of",
  "all of a sudden",
  "at the moment",
  "on time",
  "in charge of",
  "how much",
  "united states",
  "usa",
  "u.s",
  "u.s."
];

// Function to find multi-word phrases in text
export const findMultiWordPhrases = (text: string): Array<{phrase: string, start: number, end: number}> => {
  const found: Array<{phrase: string, start: number, end: number}> = [];
  // Normalize apostrophes (curly quotes to straight quotes) and lowercase
  const normalizedText = text.toLowerCase().replace(/[\u2018\u2019]/g, "'");
  
  // Sort phrases by length (longest first) to prioritize longer phrases
  const sortedPhrases = [...MULTI_WORD_PHRASES].sort((a, b) => b.length - a.length);
  
  for (const phrase of sortedPhrases) {
    let startIndex = 0;
    while (true) {
      const index = normalizedText.indexOf(phrase, startIndex);
      if (index === -1) break;
      
      // Check if this phrase overlaps with any already found phrase
      const overlaps = found.some(existing => 
        (index >= existing.start && index < existing.end) ||
        (index + phrase.length > existing.start && index + phrase.length <= existing.end) ||
        (index < existing.start && index + phrase.length > existing.end)
      );
      
      if (!overlaps) {
        // Check if the phrase is surrounded by word boundaries
        // At start/end of string, consider it a valid boundary
        const isStartBoundary = index === 0 || /\s|[.,!?;:()[\]{}"-]/.test(normalizedText[index - 1]);
        const isEndBoundary = index + phrase.length === normalizedText.length || /\s|[.,!?;:()[\]{}"-]/.test(normalizedText[index + phrase.length]);
        
        if (isStartBoundary && isEndBoundary) {
          found.push({
            phrase,
            start: index,
            end: index + phrase.length
          });
        }
      }
      
      startIndex = index + 1;
    }
  }
  
  // Sort by start position
  return found.sort((a, b) => a.start - b.start);
};

// Function to check if a given text is a multi-word phrase
export const isMultiWordPhrase = (text: string): boolean => {
  const normalizedText = text.toLowerCase().trim();
  return MULTI_WORD_PHRASES.includes(normalizedText);
};
