-- Add lessons 21-35 to Vídeo aulas - Gramática chapter
INSERT INTO content_items (chapter_id, title, content, "order") VALUES
-- Find the chapter_id for "Vídeo aulas - Gramática" and insert lessons 21-35
((SELECT id FROM content_chapters WHERE title = 'Vídeo aulas - Gramática' AND language = 'en'), 'Lesson for Vídeo aulas - Gramática 21', '{"type": "ttsArticle", "title": "Lesson for Vídeo aulas - Gramática 21", "imageUrl": "/lovable-uploads/ee17148f-42bc-4604-b957-e1eef4503b88.png", "displayText": "This is lesson 21 for Vídeo aulas - Gramática.", "audioText": "This is lesson 21 for Vídeo aulas - Gramática."}', 21),
((SELECT id FROM content_chapters WHERE title = 'Vídeo aulas - Gramática' AND language = 'en'), 'Lesson for Vídeo aulas - Gramática 22', '{"type": "ttsArticle", "title": "Lesson for Vídeo aulas - Gramática 22", "imageUrl": "/lovable-uploads/ee17148f-42bc-4604-b957-e1eef4503b88.png", "displayText": "This is lesson 22 for Vídeo aulas - Gramática.", "audioText": "This is lesson 22 for Vídeo aulas - Gramática."}', 22),
((SELECT id FROM content_chapters WHERE title = 'Vídeo aulas - Gramática' AND language = 'en'), 'Lesson for Vídeo aulas - Gramática 23', '{"type": "ttsArticle", "title": "Lesson for Vídeo aulas - Gramática 23", "imageUrl": "/lovable-uploads/ee17148f-42bc-4604-b957-e1eef4503b88.png", "displayText": "This is lesson 23 for Vídeo aulas - Gramática.", "audioText": "This is lesson 23 for Vídeo aulas - Gramática."}', 23),
((SELECT id FROM content_chapters WHERE title = 'Vídeo aulas - Gramática' AND language = 'en'), 'Lesson for Vídeo aulas - Gramática 24', '{"type": "ttsArticle", "title": "Lesson for Vídeo aulas - Gramática 24", "imageUrl": "/lovable-uploads/ee17148f-42bc-4604-b957-e1eef4503b88.png", "displayText": "This is lesson 24 for Vídeo aulas - Gramática.", "audioText": "This is lesson 24 for Vídeo aulas - Gramática."}', 24),
((SELECT id FROM content_chapters WHERE title = 'Vídeo aulas - Gramática' AND language = 'en'), 'Lesson for Vídeo aulas - Gramática 25', '{"type": "ttsArticle", "title": "Lesson for Vídeo aulas - Gramática 25", "imageUrl": "/lovable-uploads/ee17148f-42bc-4604-b957-e1eef4503b88.png", "displayText": "This is lesson 25 for Vídeo aulas - Gramática.", "audioText": "This is lesson 25 for Vídeo aulas - Gramática."}', 25),
((SELECT id FROM content_chapters WHERE title = 'Vídeo aulas - Gramática' AND language = 'en'), 'Lesson for Vídeo aulas - Gramática 26', '{"type": "ttsArticle", "title": "Lesson for Vídeo aulas - Gramática 26", "imageUrl": "/lovable-uploads/ee17148f-42bc-4604-b957-e1eef4503b88.png", "displayText": "This is lesson 26 for Vídeo aulas - Gramática.", "audioText": "This is lesson 26 for Vídeo aulas - Gramática."}', 26),
((SELECT id FROM content_chapters WHERE title = 'Vídeo aulas - Gramática' AND language = 'en'), 'Lesson for Vídeo aulas - Gramática 27', '{"type": "ttsArticle", "title": "Lesson for Vídeo aulas - Gramática 27", "imageUrl": "/lovable-uploads/ee17148f-42bc-4604-b957-e1eef4503b88.png", "displayText": "This is lesson 27 for Vídeo aulas - Gramática.", "audioText": "This is lesson 27 for Vídeo aulas - Gramática."}', 27),
((SELECT id FROM content_chapters WHERE title = 'Vídeo aulas - Gramática' AND language = 'en'), 'Lesson for Vídeo aulas - Gramática 28', '{"type": "ttsArticle", "title": "Lesson for Vídeo aulas - Gramática 28", "imageUrl": "/lovable-uploads/ee17148f-42bc-4604-b957-e1eef4503b88.png", "displayText": "This is lesson 28 for Vídeo aulas - Gramática.", "audioText": "This is lesson 28 for Vídeo aulas - Gramática."}', 28),
((SELECT id FROM content_chapters WHERE title = 'Vídeo aulas - Gramática' AND language = 'en'), 'Lesson for Vídeo aulas - Gramática 29', '{"type": "ttsArticle", "title": "Lesson for Vídeo aulas - Gramática 29", "imageUrl": "/lovable-uploads/ee17148f-42bc-4604-b957-e1eef4503b88.png", "displayText": "This is lesson 29 for Vídeo aulas - Gramática.", "audioText": "This is lesson 29 for Vídeo aulas - Gramática."}', 29),
((SELECT id FROM content_chapters WHERE title = 'Vídeo aulas - Gramática' AND language = 'en'), 'Lesson for Vídeo aulas - Gramática 30', '{"type": "ttsArticle", "title": "Lesson for Vídeo aulas - Gramática 30", "imageUrl": "/lovable-uploads/ee17148f-42bc-4604-b957-e1eef4503b88.png", "displayText": "This is lesson 30 for Vídeo aulas - Gramática.", "audioText": "This is lesson 30 for Vídeo aulas - Gramática."}', 30),
((SELECT id FROM content_chapters WHERE title = 'Vídeo aulas - Gramática' AND language = 'en'), 'Lesson for Vídeo aulas - Gramática 31', '{"type": "ttsArticle", "title": "Lesson for Vídeo aulas - Gramática 31", "imageUrl": "/lovable-uploads/ee17148f-42bc-4604-b957-e1eef4503b88.png", "displayText": "This is lesson 31 for Vídeo aulas - Gramática.", "audioText": "This is lesson 31 for Vídeo aulas - Gramática."}', 31),
((SELECT id FROM content_chapters WHERE title = 'Vídeo aulas - Gramática' AND language = 'en'), 'Lesson for Vídeo aulas - Gramática 32', '{"type": "ttsArticle", "title": "Lesson for Vídeo aulas - Gramática 32", "imageUrl": "/lovable-uploads/ee17148f-42bc-4604-b957-e1eef4503b88.png", "displayText": "This is lesson 32 for Vídeo aulas - Gramática.", "audioText": "This is lesson 32 for Vídeo aulas - Gramática."}', 32),
((SELECT id FROM content_chapters WHERE title = 'Vídeo aulas - Gramática' AND language = 'en'), 'Lesson for Vídeo aulas - Gramática 33', '{"type": "ttsArticle", "title": "Lesson for Vídeo aulas - Gramática 33", "imageUrl": "/lovable-uploads/ee17148f-42bc-4604-b957-e1eef4503b88.png", "displayText": "This is lesson 33 for Vídeo aulas - Gramática.", "audioText": "This is lesson 33 for Vídeo aulas - Gramática."}', 33),
((SELECT id FROM content_chapters WHERE title = 'Vídeo aulas - Gramática' AND language = 'en'), 'Lesson for Vídeo aulas - Gramática 34', '{"type": "ttsArticle", "title": "Lesson for Vídeo aulas - Gramática 34", "imageUrl": "/lovable-uploads/ee17148f-42bc-4604-b957-e1eef4503b88.png", "displayText": "This is lesson 34 for Vídeo aulas - Gramática.", "audioText": "This is lesson 34 for Vídeo aulas - Gramática."}', 34),
((SELECT id FROM content_chapters WHERE title = 'Vídeo aulas - Gramática' AND language = 'en'), 'Lesson for Vídeo aulas - Gramática 35', '{"type": "ttsArticle", "title": "Lesson for Vídeo aulas - Gramática 35", "imageUrl": "/lovable-uploads/ee17148f-42bc-4604-b957-e1eef4503b88.png", "displayText": "This is lesson 35 for Vídeo aulas - Gramática.", "audioText": "This is lesson 35 for Vídeo aulas - Gramática."}', 35);