// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcuquzgpaeoqskesgcnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jdXF1emdwYWVvcXNrZXNnY254Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODM1MjcsImV4cCI6MjA2MTY1OTUyN30.vGIcy1PzEQ_OE3PYEVQGK1XC1iPfLA6kWTVG2dpiWqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});